name: release
on:
  push:
    branches:
      - release

jobs:
  build-clients:
    name: build-clients
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci
        working-directory: ./editors/code

      - run: npm run package --scripts-prepend-node-path
        working-directory: ./editors/code

      - name: Copy vscode extension
        run: mkdir -p ./dist/code && cp ./editors/code/rust-analyzer.vsix ./dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: editor-plugins
          path: ./dist

  make-release:
    name: make-release
    runs-on: ubuntu-latest
    # needs: ['build-server', 'build-clients']
    steps:
      - name: Install Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: echo "::set-env name=TAG::$(date --iso)"
      - run: 'echo "TAG: $TAG"'

      - name: Checkout repository
        uses: actions/checkout@v1

      - run: npm ci
        working-directory: ./editors/code

      - name: Publish Extension
        working-directory: ./editors/code
        # token from https://dev.azure.com/rust-analyzer/
        run: npx vsce publish 0.1.$(date +%Y%m%d) --pat ${{ secrets.MARKETPLACE_TOKEN }}
